(() => {
  'use strict';
  const words={
    'zh-Hant':{title:'從樣本重算詞頻',before:'目前詞頻',after:'重算後',words:'詞彙數',spam_total:'垃圾類詞頻總數',ham_total:'正常類詞頻總數',sample_rows:'原始樣本數',spam_docs:'參與重算：垃圾',ham_docs:'參與重算：正常',added:'新增詞彙',removed:'移除詞彙',changed:'詞頻改變',impact:'按現有樣本及分詞方式重新計算，所有人工詞頻調整都會被取代。保留樣本與標籤，不會清理重複或衝突資料，也不改變門檻。',existing:'影響之後的模型判斷。既有封禁與待執行案件不會自動重判或撤銷。',ack:'我已確認變化，並了解人工詞頻會被取代。',confirm:'確認重算',retry:'重試同一操作',reload:'重新預覽',close:'關閉',loading:'正在處理…',saved:'詞頻已重算',undo:'已保存原詞頻。尚未有新訓練或模型修改時，可私訊機器人復原：',settings_changed:'模型、樣本或程式已變動。請重新預覽後確認。',save_failed:'暫時無法確認結果。重試會查回同一操作，不會重算兩次。',temporarily_unavailable:'暫時無法處理，請稍後再試。',rate_limited:'模型檢查正在執行，請稍後再試。',model_too_large:'資料超出面板重算上限，未作修改。請使用離線維護流程。',invalid_request:'請重新預覽後再試。'},
    'zh-Hans':{title:'从样本重算词频',before:'当前词频',after:'重算后',words:'词汇数',spam_total:'垃圾类词频总数',ham_total:'正常类词频总数',sample_rows:'原始样本数',spam_docs:'参与重算：垃圾',ham_docs:'参与重算：正常',added:'新增词汇',removed:'移除词汇',changed:'词频改变',impact:'按现有样本及分词方式重新计算，所有人工词频调整都会被取代。保留样本与标签，不会清理重复或冲突数据，也不改变阈值。',existing:'影响之后的模型判断。既有封禁与待执行案件不会自动重判或撤销。',ack:'我已确认变化，并了解人工词频会被取代。',confirm:'确认重算',retry:'重试同一操作',reload:'重新预览',close:'关闭',loading:'正在处理…',saved:'词频已重算',undo:'已保存原词频。尚未有新训练或模型修改时，可私信机器人恢复：',settings_changed:'模型、样本或程序已变动。请重新预览后确认。',save_failed:'暂时无法确认结果。重试会查回同一操作，不会重算两次。',temporarily_unavailable:'暂时无法处理，请稍后再试。',rate_limited:'模型检查正在执行，请稍后再试。',model_too_large:'数据超出面板重算上限，未作修改。请使用离线维护流程。',invalid_request:'请重新预览后再试。'},
    en:{title:'Recalculate token counts from samples',before:'Current counts',after:'After recalculation',words:'Vocabulary size',spam_total:'Total spam token counts',ham_total:'Total normal token counts',sample_rows:'Raw samples',spam_docs:'Spam samples used',ham_docs:'Normal samples used',added:'Tokens added',removed:'Tokens removed',changed:'Counts changed',impact:'Recalculates counts using saved samples and the current tokenizer, replacing all manual token adjustments. Samples, labels and thresholds stay unchanged; duplicates and conflicting labels are not cleaned up.',existing:'Affects future model decisions. Existing bans and pending cases are not automatically reassessed or reversed.',ack:'I reviewed the changes and understand that manual token adjustments will be replaced.',confirm:'Confirm recalculation',retry:'Retry this operation',reload:'Refresh preview',close:'Close',loading:'Working…',saved:'Token counts recalculated',undo:'The previous counts are saved. Before any further training or model change, send the bot this command to restore them:',settings_changed:'The model, samples or code changed. Refresh the preview before confirming.',save_failed:'The result could not be confirmed. Retrying checks the same operation; it will not recalculate twice.',temporarily_unavailable:'Unable to process the request. Try again shortly.',rate_limited:'Another model check is running. Try again shortly.',model_too_large:'The dataset exceeds panel limits. Nothing changed. Use the offline maintenance workflow.',invalid_request:'Refresh the preview and try again.'}
  };
  let dialog,context,lang='zh-Hant',snapshot=null,pending=null,result=null,ack=false,busy=false,conflict=false,error='';
  const t=k=>words[lang][k]||words[lang].temporarily_unavailable;
  const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
  function button(key,action){const b=el('button',t(key));b.type='button';b.disabled=busy;b.addEventListener('click',action);return b;}
  function counts(values,keys){const dl=el('dl');for(const key of keys)dl.append(el('dt',t(key)),el('dd',Number(values[key]).toLocaleString(lang)));return dl;}
  function close(){if(!busy)dialog.close();}
  function render(){
    if(!dialog?.open)return;dialog.replaceChildren();const heading=el('h2',t('title'));heading.id='rebuild-heading';dialog.append(heading);
    const status=el('p',error?t(error):busy?t('loading'):result?t('saved'):'',error?'host-error':'');status.setAttribute('role',error?'alert':'status');dialog.append(status);
    if(result){dialog.append(el('p',t('undo'),'host-note'),el('pre',`/revert ${result.action_id}`));}
    else if(snapshot){
      const info=el('article',undefined,'host-record');info.append(counts(snapshot,['sample_rows','spam_docs','ham_docs']));dialog.append(info);
      const table=el('table',undefined,'rebuild-diff');const head=el('thead');const header=el('tr');for(const text of ['',t('before'),t('after')]){const th=el('th',text);th.scope='col';header.append(th);}head.append(header);table.append(head);const body=el('tbody');for(const key of ['words','spam_total','ham_total']){const row=el('tr');const label=el('th',t(key));label.scope='row';row.append(label,...['before','after'].map(which=>el('td',Number(snapshot[which][key]).toLocaleString(lang))));body.append(row);}table.append(body);dialog.append(table);
      const changes=el('article',undefined,'host-record');changes.append(counts(snapshot.changes,['added','removed','changed']));dialog.append(changes,el('p',t('impact'),'host-note'),el('p',t('existing'),'host-note'));
      const label=el('label',undefined,'rebuild-ack');const input=el('input');input.type='checkbox';input.checked=ack;input.disabled=busy||!!pending;input.addEventListener('change',()=>{ack=input.checked;const confirm=dialog.querySelector('[data-confirm-rebuild]');if(confirm)confirm.disabled=busy||conflict||!ack;});label.append(input,el('span',t('ack')));dialog.append(label);
      const confirm=button(pending?'retry':'confirm',save);confirm.dataset.confirmRebuild='';confirm.className='primary';confirm.disabled=busy||conflict||!ack;dialog.append(confirm);
    }
    const actions=el('div',undefined,'dialog-actions');const reload=button('reload',read);reload.disabled=busy||!!pending;actions.append(reload,button('close',close));dialog.append(actions);
  }
  function fail(e){if(['session_expired','forbidden'].includes(e.message)){window.SPBModelRebuild.expire();context.onAuthError(e);return;}error=Object.hasOwn(words.en,e.message)?e.message:'temporarily_unavailable';if(['settings_changed','invalid_request','model_too_large'].includes(error)){pending=null;conflict=true;}}
  async function read(){if(busy||pending)return;busy=true;error='';snapshot=null;result=null;ack=false;conflict=false;render();try{snapshot=await context.request('host-model-rebuild','POST',{});}catch(e){fail(e);}finally{busy=false;render();}}
  async function save(){if(busy||conflict||!ack||!snapshot)return;pending??={request_id:crypto.randomUUID(),expected_revision:snapshot.revision};busy=true;error='';render();try{result=await context.request('host-model-rebuild','PATCH',pending);pending=null;await context.onSaved();}catch(e){fail(e);}finally{busy=false;render();}}
  window.SPBModelRebuild={
    open(options){context=options;lang=options.language;if(!dialog){dialog=el('dialog',undefined,'host-rebuild-dialog');dialog.setAttribute('aria-labelledby','rebuild-heading');dialog.addEventListener('cancel',e=>{e.preventDefault();close();});document.body.append(dialog);}dialog.showModal();if(pending){error='save_failed';render();}else read();},
    setLanguage(value){lang=value;render();},back(){if(dialog?.open){close();return true;}return false;},expire(){if(dialog?.open)dialog.close();snapshot=null;pending=null;result=null;ack=false;}
  };
})();
