(() => {
  'use strict';
  const words={
    'zh-Hant':{
      title:'模型檢查',threshold:'全域門檻',invalidThreshold:'門檻無效，無法比較。',samples:'訓練資料',rows:'原始筆數',spam:'垃圾樣本',ham:'正常樣本',invalid:'無效標籤',newest:'最近樣本',spam_docs:'模型垃圾文件數',ham_docs:'模型正常文件數',spam_vocabulary:'垃圾類詞彙數',ham_vocabulary:'正常類詞彙數',overrides:'查看另設門檻的群組',policy:'各群門檻只影響本群判斷；聯防收錄仍按全域條件檢查。',
      reviews:'近期訓練審核',since:'統計起點',approved:'批准訓練',rejected:'拒絕訓練',reviewNote:'最近 30 天的人工訓練審核。拒絕訓練不等於誤封，這些數字不能當作線上誤判率。',
      trial:'試算文字',text:'文字（最多 4,000 字）',score:'模型分數',runScore:'計算分數',scoreNote:'只測目前模型，不檢查規則、群組模組、白名單或 Telegram 權限；不會封禁或訓練。分數不是已校準的垃圾訊息機率。',passed:'達到全域分數門檻',notPassed:'未達全域分數門檻',empty:'沒有可供模型使用的詞。',tokens:'詞語影響',token:'詞語',spam_count:'垃圾樣本中的出現次數',ham_count:'正常樣本中的出現次數',delta:'對分數的影響',higher:'推高',lower:'拉低',neutral:'中性',tokenNote:'依影響大小排列，最多列出 80 個詞。影響值是對數權重，不是機率。',token_count:'有效詞數',
      evaluation:'離線評估',runEvaluation:'評估現有樣本',evalNote:'相同詞袋只算一組，排除重複、空詞及衝突標籤；約 20% 留作測試。用其餘資料建立臨時模型，不改動正式模型。',limitation:'這是既有標籤的回顧測試，不能代表實際群組誤封率，也不會自動調低門檻。',too_large:'資料超出面板評估上限，未抽樣或執行評估。請使用離線工具處理完整資料。',invalid_threshold:'目前門檻無效，未執行評估。',insufficient:'可用資料不足：至少 20 組，且訓練和測試都須有垃圾、正常樣本。',
      usable_groups:'可用詞袋組數',empty_rows:'無有效詞',invalid_labels:'無效標籤',duplicate_rows:'重複筆數',conflicting_groups:'標籤衝突組數',conflicting_rows:'衝突筆數',train_spam:'訓練：垃圾',train_ham:'訓練：正常',test_spam:'測試：垃圾',test_ham:'測試：正常',precision:'精確率',recall:'召回率',false_positive:'正常判成垃圾',false_negative:'垃圾漏放',true_positive:'正確攔截垃圾',true_negative:'正確放行正常',current:'本次全域門檻',fingerprint:'樣本快照識別碼',snapshot:'資料時間',busy:'正在計算…',unknown:'未知',retry:'暫時無法計算，請重試。',rate_limited:'模型檢查正在執行，請稍後再試。',invalid_request:'請檢查輸入，最多 4,000 字。'
    },
    'zh-Hans':{
      title:'模型检查',threshold:'全局阈值',invalidThreshold:'阈值无效，无法比较。',samples:'训练数据',rows:'原始条数',spam:'垃圾样本',ham:'正常样本',invalid:'无效标签',newest:'最近样本',spam_docs:'模型垃圾文档数',ham_docs:'模型正常文档数',spam_vocabulary:'垃圾类词汇数',ham_vocabulary:'正常类词汇数',overrides:'查看另设阈值的群组',policy:'各群阈值只影响本群判断；联防收录仍按全局条件检查。',
      reviews:'近期训练审核',since:'统计起点',approved:'批准训练',rejected:'拒绝训练',reviewNote:'最近 30 天的人工训练审核。拒绝训练不等于误封，这些数字不能当作线上误判率。',
      trial:'试算文字',text:'文字（最多 4,000 字）',score:'模型分数',runScore:'计算分数',scoreNote:'只测试当前模型，不检查规则、群组模块、白名单或 Telegram 权限；不会封禁或训练。分数不是已校准的垃圾消息概率。',passed:'达到全局分数阈值',notPassed:'未达全局分数阈值',empty:'没有可供模型使用的词。',tokens:'词语影响',token:'词语',spam_count:'垃圾样本中的出现次数',ham_count:'正常样本中的出现次数',delta:'对分数的影响',higher:'推高',lower:'拉低',neutral:'中性',tokenNote:'按影响大小排列，最多列出 80 个词。影响值是对数权重，不是概率。',token_count:'有效词数',
      evaluation:'离线评估',runEvaluation:'评估现有样本',evalNote:'相同词袋只算一组，排除重复、空词及冲突标签；约 20% 留作测试。用其余数据建立临时模型，不改动正式模型。',limitation:'这是既有标签的回顾测试，不能代表实际群组误封率，也不会自动调低阈值。',too_large:'数据超出面板评估上限，未抽样或执行评估。请使用离线工具处理完整数据。',invalid_threshold:'当前阈值无效，未执行评估。',insufficient:'可用数据不足：至少 20 组，且训练和测试都须有垃圾、正常样本。',
      usable_groups:'可用词袋组数',empty_rows:'无有效词',invalid_labels:'无效标签',duplicate_rows:'重复条数',conflicting_groups:'标签冲突组数',conflicting_rows:'冲突条数',train_spam:'训练：垃圾',train_ham:'训练：正常',test_spam:'测试：垃圾',test_ham:'测试：正常',precision:'精确率',recall:'召回率',false_positive:'正常判成垃圾',false_negative:'垃圾漏放',true_positive:'正确拦截垃圾',true_negative:'正确放行正常',current:'本次全局阈值',fingerprint:'样本快照识别码',snapshot:'数据时间',busy:'正在计算…',unknown:'未知',retry:'暂时无法计算，请重试。',rate_limited:'模型检查正在执行，请稍后再试。',invalid_request:'请检查输入，最多 4,000 字。'
    },
    en:{
      title:'Model checks',threshold:'Global threshold',invalidThreshold:'Invalid threshold; comparison unavailable.',samples:'Training data',rows:'Raw rows',spam:'Spam samples',ham:'Normal samples',invalid:'Invalid labels',newest:'Latest sample',spam_docs:'Model spam documents',ham_docs:'Model normal documents',spam_vocabulary:'Spam vocabulary',ham_vocabulary:'Normal vocabulary',overrides:'View groups with custom thresholds',policy:'Group thresholds affect local checks. Shared bans still require the global admission criteria.',
      reviews:'Recent training reviews',since:'Counted since',approved:'Training approved',rejected:'Training rejected',reviewNote:'Manual training reviews over the last 30 days. Rejected training does not establish a mistaken ban; these counts are not a live false-positive rate.',
      trial:'Score text',text:'Text (up to 4,000 characters)',score:'Model score',runScore:'Calculate score',scoreNote:'Tests the current model only, without rules, group modules, exemptions or Telegram permissions. It does not ban or train. The score is not a calibrated probability of spam.',passed:'Meets the global score threshold',notPassed:'Below the global score threshold',empty:'No usable tokens.',tokens:'Token influence',token:'Token',spam_count:'Occurrences in spam samples',ham_count:'Occurrences in normal samples',delta:'Score influence',higher:'Raises',lower:'Lowers',neutral:'Neutral',tokenNote:'Up to 80 tokens, ordered by influence. Values are log weights, not probabilities.',token_count:'Usable tokens',
      evaluation:'Offline evaluation',runEvaluation:'Evaluate saved samples',evalNote:'Identical feature bags stay together; duplicates, empty features and conflicting labels are excluded. About 20% is held out for testing. The remaining data trains a temporary model; the live model is unchanged.',limitation:'This retrospective test uses existing labels. It is not a live false-positive rate and does not lower thresholds automatically.',too_large:'The dataset exceeds panel limits. No sampling or evaluation was performed. Use the offline tool for the complete dataset.',invalid_threshold:'The current threshold is invalid. Evaluation did not run.',insufficient:'Not enough usable data: at least 20 groups are needed, with spam and normal samples in both training and test sets.',
      usable_groups:'Usable feature groups',empty_rows:'Empty features',invalid_labels:'Invalid labels',duplicate_rows:'Duplicate rows',conflicting_groups:'Conflicting label groups',conflicting_rows:'Conflicting rows',train_spam:'Training: spam',train_ham:'Training: normal',test_spam:'Test: spam',test_ham:'Test: normal',precision:'Precision',recall:'Recall',false_positive:'Normal flagged as spam',false_negative:'Spam missed',true_positive:'Spam caught',true_negative:'Normal allowed',current:'Global threshold for this run',fingerprint:'Sample snapshot ID',snapshot:'Snapshot time',busy:'Calculating…',unknown:'Unknown',retry:'Unable to calculate. Please retry.',rate_limited:'Another model check is running. Please try again shortly.',invalid_request:'Check the input; the limit is 4,000 characters.'
    }
  };
  Object.assign(words['zh-Hant'],{modelDetails:'模型細節',trialThreshold:'測試門檻',usable_groups:'可用樣本組數',evalNote:'含有相同有效詞的樣本歸為一組，排除重複、空詞及衝突標籤；約 20% 留作測試。用其餘資料建立臨時模型，不改動正式模型。'});
  Object.assign(words['zh-Hans'],{modelDetails:'模型详情',trialThreshold:'测试阈值',usable_groups:'可用样本组数',evalNote:'含有相同有效词的样本归为一组，排除重复、空词及冲突标签；约 20% 留作测试。用其余数据建立临时模型，不改动正式模型。'});
  Object.assign(words.en,{modelDetails:'Model details',trialThreshold:'Test threshold',usable_groups:'Usable sample groups',evalNote:'Samples with the same usable tokens stay together; duplicates, empty features and conflicting labels are excluded. About 20% is held out for testing. The remaining data trains a temporary model; the live model is unchanged.'});
  let root,options,summary,draft='',score=null,evaluation=null,busy=false,error='',generation=0;
  const t=key=>words[options.language][key]??key;
  const el=(tag,text,className)=>{const node=document.createElement(tag);if(text!==undefined)node.textContent=text;if(className)node.className=className;return node;};
  const date=value=>value?new Date(typeof value==='number'?value*1000:value).toLocaleString(options.language):t('unknown');
  const number=value=>value===null||value===undefined?'—':Number(value).toLocaleString(options.language,{maximumFractionDigits:6});
  function button(key,action){const b=el('button',t(key));b.type='button';b.disabled=busy;b.addEventListener('click',action);return b;}
  function details(values){const dl=el('dl');for(const [key,value] of values)dl.append(el('dt',t(key)),el('dd',String(value)));return dl;}
  function section(title){const node=el('section',undefined,'host-record');node.append(el('h2',t(title)));root.append(node);return node;}
  function render(){
    if(!root?.isConnected)return;
    root.replaceChildren();
    const status=el('p',error?t(error):busy?t('busy'):'',error?'host-error':'host-meta');status.setAttribute('role','status');status.setAttribute('aria-live','polite');root.append(status);
    const data=section('samples');data.append(details([['threshold',summary.global_threshold===null?t('invalidThreshold'):number(summary.global_threshold)],...['rows','spam','ham','invalid'].map(k=>[k,number(summary.samples[k])]),['newest',date(summary.samples.newest)]]));const modelDetails=el('details');modelDetails.append(el('summary',t('modelDetails')),details(['spam_docs','ham_docs','spam_vocabulary','ham_vocabulary'].map(k=>[k,number(summary.model[k])])));data.append(modelDetails,button('overrides',options.onGroups),el('p',`${number(summary.group_overrides)} · ${t('policy')}`,'host-note'));
    const reviews=section('reviews');reviews.append(details([['since',date(summary.training_reviews.since)],['approved',number(summary.training_reviews.approved)],['rejected',number(summary.training_reviews.rejected)]]),el('p',t('reviewNote'),'host-note'));
    const trial=section('trial');trial.append(el('p',t('scoreNote'),'host-note'));
    const form=el('form',undefined,'host-rule-form');const label=el('label',t('text'));label.htmlFor='model-text';const input=el('textarea');input.id='model-text';input.rows=4;input.maxLength=8000;input.value=draft;input.disabled=busy;input.addEventListener('input',()=>{draft=input.value;score=null;result.replaceChildren();input.setCustomValidity(Array.from(draft).length>4000?t('invalid_request'):'');});label.append(input);form.append(label);const submit=el('button',t('runScore'));submit.type='submit';submit.disabled=busy;form.append(submit);form.addEventListener('submit',event=>{event.preventDefault();if(!busy&&form.reportValidity())run('score');});trial.append(form);
    const result=el('div');trial.append(result);
    if(score){result.append(details([['snapshot',date(score.updated_at)],['score',number(score.score)],['threshold',number(score.global_threshold)],['token_count',number(score.token_count)]]),el('p',t(score.passes_global===null?'invalidThreshold':score.passes_global?'passed':'notPassed')));if(!score.token_count)result.append(el('p',t('empty')));
      if(score.tokens.length){const fold=el('details');fold.append(el('summary',t('tokens')),el('p',t('tokenNote'),'host-note'));for(const token of score.tokens){const item=el('div',undefined,'model-token');item.append(el('strong',token.token),details([['spam_count',number(token.spam_count)],['ham_count',number(token.ham_count)],['delta',`${t(token.delta>0?'higher':token.delta<0?'lower':'neutral')} ${number(Math.abs(token.delta))}`]]));fold.append(item);}result.append(fold);}}
    const test=section('evaluation');test.append(el('p',t('evalNote'),'host-note'),button('runEvaluation',()=>run('evaluate')),el('p',t('limitation'),'host-note'));
    if(evaluation){test.append(details([['snapshot',date(evaluation.updated_at)]]));if(evaluation.status!=='ready'){test.append(el('p',t(evaluation.status)));return;}
      const r=evaluation.report;test.append(details([...['rows','usable_groups','empty_rows','invalid_labels','duplicate_rows','conflicting_groups','conflicting_rows'].map(k=>[k,number(r.corpus[k])]),...['train_spam','train_ham','test_spam','test_ham'].map(k=>[k,number(r[k])])]));
      if(!r.thresholds.length)test.append(el('p',t('insufficient')));
      for(const row of r.thresholds){const fold=el('details');fold.className='model-threshold';const current=Math.abs(row.threshold-r.live_threshold)<1e-9;fold.append(el('summary',`${t('trialThreshold')} ${number(row.threshold)}${current?' · '+t('current'):''}`));fold.open=current;fold.append(details(['true_positive','false_positive','false_negative','true_negative','precision','recall'].map(k=>[k,['precision','recall'].includes(k)&&row[k]!==null?`${(row[k]*100).toLocaleString(options.language,{maximumFractionDigits:1})}%`:number(row[k])])));test.append(fold);}
      const provenance=el('details');provenance.append(el('summary',t('fingerprint')),el('p',evaluation.sample_fingerprint,'host-meta'));test.append(provenance);
    }
  }
  async function run(action){if(busy)return;const current=generation;busy=true;error='';if(action==='score')score=null;else evaluation=null;render();try{const result=await options.request('host-model','POST',{action,...(action==='score'?{text:draft}:{})});if(current!==generation)return;if(action==='score')score=result;else evaluation=result;}catch(e){if(['session_expired','forbidden'].includes(e.message)){options.onAuthError(e);return;}if(current===generation)error=Object.hasOwn(words.en,e.message)?e.message:'retry';}finally{if(current===generation){busy=false;render();}}}
  window.SPBModelPage={mount(target,data,opts){root=target;summary=data;options=opts;render();},reset(){generation++;draft='';score=null;evaluation=null;error='';busy=false;root=null;}};
})();
