(() => {
  'use strict';
  const words={
    'zh-Hant':{title:'退群',unknown:'群組名稱未記錄',reason:'退群理由',example:'例如：群組沒有給予機器人足夠的權限',block:'同時禁止本群重新加入機器人',blocked:'本群已被禁止重新加入；單純退群不會解除現有禁令。',scope:'會嘗試把理由發到群內，然後退出。通知發不出去仍會退群。',allow:'退群後，群管理員仍可重新加入機器人。',deny:'重新加入也會被拒絕。解除請由維護員使用 /forgive。',irreversible:'退群無法自動撤銷；需要群管理員重新邀請機器人。',protected:'這是項目使用的群組或頻道，不能在此退群。',review:'查看退群內容',confirm:'確認退群',back:'返回修改',close:'關閉',reload:'重新讀取',loading:'處理中…',retry:'重試同一請求',newRequest:'重新確認退群',last:'最近一次退群',state:'退群狀態',notice:'群內通知',queued:'已排隊，尚未退群',leaving:'已發出退群，等待確認',unconfirmed:'結果未確認，正在核對',done:'已確認離開',failed:'退群未完成，請重新確認後重試',cancelled:'已取消',skipped:'未發送（機器人已離開）',pending:'尚未發送',sent:'已發送',noticeFailed:'通知未送達',noticeUnknown:'通知結果不明',error:'退群錯誤',noticeError:'通知錯誤',audit:'操作記錄',reasonRequired:'請填寫退群理由（最多 500 字）。',save_failed:'尚未確認請求是否收到。請重試同一請求。',temporarily_unavailable:'暫時無法讀取，請重試。',settings_changed:'群組記錄已變更，請重新讀取再確認。',invalid_request:'請求無效，請重新讀取。',rate_limited:'操作太頻繁，請稍後再試。'},
    en:{title:'Leave group',unknown:'Group name not recorded',reason:'Reason for leaving',example:'For example: the bot does not have enough permissions',block:'Also prevent this group from adding the bot again',blocked:'This group already has a service ban. Leaving will not remove it.',scope:'The bot will try to post this reason, then leave. A failed notice will not prevent departure.',allow:'Group admins can invite the bot again after it leaves.',deny:'Invitations will be refused. A maintainer can lift this with /forgive.',irreversible:'Departure cannot be undone automatically. A group admin must invite the bot again.',protected:'This is a project group or channel. Departure is unavailable.',review:'Review departure',confirm:'Confirm departure',back:'Back to editing',close:'Close',reload:'Reload',loading:'Working…',retry:'Retry the same request',newRequest:'Confirm another attempt',last:'Latest departure',state:'Departure status',notice:'Group notice',queued:'Queued; not yet left',leaving:'Departure sent; awaiting confirmation',unconfirmed:'Unconfirmed; checking membership',done:'Confirmed absent',failed:'Not completed; confirm again to retry',cancelled:'Cancelled',skipped:'Not sent (bot already absent)',pending:'Not sent yet',sent:'Sent',noticeFailed:'Notice not delivered',noticeUnknown:'Notice result unknown',error:'Departure error',noticeError:'Notice error',audit:'Activity record',reasonRequired:'Enter a reason of up to 500 characters.',save_failed:'Receipt is unconfirmed. Retry the same request.',temporarily_unavailable:'Unable to load. Please retry.',settings_changed:'The group record changed. Reload before confirming.',invalid_request:'Invalid request. Please reload.',rate_limited:'Too many requests. Please try again shortly.'}
  };
  words['zh-Hans']={...words['zh-Hant'],title:'退群',unknown:'群组名称未记录',reason:'退群理由',example:'例如：群组没有给予机器人足够的权限',block:'同时禁止本群重新加入机器人',blocked:'本群已被禁止重新加入；单纯退群不会解除现有禁令。',scope:'会尝试把理由发到群内，然后退出。通知发不出去仍会退群。',allow:'退群后，群管理员仍可重新加入机器人。',deny:'重新加入也会被拒绝。解除请由维护员使用 /forgive。',irreversible:'退群无法自动撤销；需要群管理员重新邀请机器人。',protected:'这是项目使用的群组或频道，不能在此退群。',review:'查看退群内容',confirm:'确认退群',back:'返回修改',close:'关闭',reload:'重新读取',loading:'处理中…',retry:'重试同一请求',newRequest:'重新确认退群',last:'最近一次退群',state:'退群状态',notice:'群内通知',queued:'已排队，尚未退群',leaving:'已发出退群，等待确认',unconfirmed:'结果未确认，正在核对',done:'已确认离开',failed:'退群未完成，请重新确认后重试',cancelled:'已取消',skipped:'未发送（机器人已离开）',pending:'尚未发送',sent:'已发送',noticeFailed:'通知未送达',noticeUnknown:'通知结果不明',error:'退群错误',noticeError:'通知错误',audit:'操作记录',reasonRequired:'请填写退群理由（最多 500 字）。',save_failed:'尚未确认请求是否收到。请重试同一请求。',temporarily_unavailable:'暂时无法读取，请重试。',settings_changed:'群组记录已变更，请重新读取再确认。',invalid_request:'请求无效，请重新读取。',rate_limited:'操作太频繁，请稍后重试。'};
  let opts,lang='zh-Hant',dialog,snapshot,result,pending=null,busy=false,error='',review=false,reason='',block=false,conflict=false;
  const t=k=>words[lang][k]??k;
  const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
  function button(k,fn){const n=el('button',t(k));n.type='button';n.disabled=busy;n.addEventListener('click',fn);return n;}
  function close(){if(!busy)dialog?.close();}
  function fail(e){if(['session_expired','forbidden'].includes(e.message)){window.SPBGroupDeparture.expire();opts.onAuthError(e);return;}error=Object.hasOwn(words.en,e.message)?e.message:'temporarily_unavailable';if(['settings_changed','invalid_request'].includes(error)){pending=null;conflict=true;}}
  function receipt(v){const section=el('section',undefined,'host-record');section.append(el('h3',t('last')));const dl=el('dl');for(const [k,value] of [['state',t(v.state)],['reason',v.reason],['notice',t({failed:'noticeFailed',unconfirmed:'noticeUnknown'}[v.notice_state]||v.notice_state)],['audit',`#${v.action_id}`]])dl.append(el('dt',t(k)),el('dd',value));section.append(dl);for(const [key,label] of [['last_error','error'],['notice_error','noticeError']])if(v[key])section.append(el('h4',t(label)),el('p',v[key],'host-error'));return section;}
  function render(){if(!dialog?.open)return;dialog.replaceChildren();const title=el('h2',t('title'));title.id='departure-heading';dialog.append(title);const status=el('p',error?t(error):busy?t('loading'):'',error?'host-error':'');status.setAttribute('role',error?'alert':'status');dialog.append(status);
    if(snapshot){dialog.append(el('h3',snapshot.title||t('unknown')),el('p',String(snapshot.chat_id),'host-meta'));
      if(snapshot.protected)dialog.append(el('p',t('protected')));
      else if(result){dialog.append(receipt(result));}
      else if(review){dialog.append(el('h4',t('reason')),el('p',reason),el('p',t(snapshot.service_denied?'blocked':block?'deny':'allow'),'host-note'),el('p',t('scope'),'host-note'),el('p',t('irreversible'),'host-note'));const save=button(pending?'retry':'confirm',submit);save.disabled=busy||conflict;save.className='primary';const back=button('back',()=>{review=false;render();});back.disabled=busy||!!pending;dialog.append(save,back);}
      else {
        if(snapshot.latest)dialog.append(receipt(snapshot.latest));
        if(!['queued','leaving','unconfirmed'].includes(snapshot.latest?.state)){
          const form=el('form',undefined,'host-rule-form');const label=el('label',t('reason'));const field=el('textarea');field.id='departure-reason';field.rows=3;field.maxLength=500;field.required=true;field.placeholder=t('example');field.value=reason;field.disabled=busy;field.addEventListener('input',()=>{reason=field.value;});label.htmlFor=field.id;label.append(field);form.append(label);
          if(snapshot.service_denied)form.append(el('p',t('blocked'),'host-note'));else{const label=el('label',undefined,'rebuild-ack');const check=el('input');check.type='checkbox';check.checked=block;check.disabled=busy;check.addEventListener('change',()=>{block=check.checked;});label.append(check,el('span',t('block')));form.append(label);}
          form.append(el('p',t('scope'),'host-note'));const next=el('button',t(snapshot.latest?'newRequest':'review'));next.type='submit';next.disabled=busy;form.append(next);form.addEventListener('submit',e=>{e.preventDefault();reason=field.value.trim();if(!reason||[...reason].length>500){error='reasonRequired';render();return;}error='';review=true;render();});dialog.append(form);
        }
      }
    }
    const actions=el('div',undefined,'dialog-actions');const reload=button('reload',read);reload.disabled=busy||!!pending;actions.append(reload,button('close',close));dialog.append(actions);
  }
  async function read(){if(busy||pending)return;busy=true;error='';review=false;result=null;conflict=false;render();try{snapshot=await opts.request('host-group-leave','POST',{chat_id:opts.chatId});reason=snapshot.latest?.reason||'';block=false;}catch(e){fail(e);}finally{busy=false;render();}}
  async function submit(){if(busy||conflict||!review)return;pending??={request_id:crypto.randomUUID(),chat_id:snapshot.chat_id,expected_revision:snapshot.revision,reason,block_rejoin:block};busy=true;error='';render();try{result=await opts.request('host-group-leave','PATCH',pending);pending=null;await opts.onSaved();}catch(e){fail(e);}finally{busy=false;render();}}
  window.SPBGroupDeparture={open(options){if(pending&&opts){options={...options,chatId:pending.chat_id};}else{snapshot=null;result=null;reason='';block=false;}opts=options;lang=options.language;if(!dialog){dialog=el('dialog',undefined,'host-rebuild-dialog');dialog.setAttribute('aria-labelledby','departure-heading');dialog.addEventListener('cancel',e=>{e.preventDefault();close();});document.body.append(dialog);}dialog.showModal();if(pending){error='save_failed';render();}else read();},setLanguage(v){lang=v;render();},back(){if(dialog?.open){close();return true;}return false;},expire(){dialog?.close();snapshot=null;result=null;pending=null;review=false;}};
})();
